[package]
name = "unawareness"
version = "0.1.0"
authors = ["Amellia <camellensatz@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
iced = { version = "0.2", features = ["image"] }
itertools = "0.10"
regex = "1.4"
minidom = "0.12"
once_cell = "1.5"
thiserror = "1.0"
