[package]
name = "unawareness"
version = "0.1.0"
authors = ["Amellia <camellensatz@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
iced = { version = "0.2", features = ["image"] }
regex = "1.4"
minidom = "0.12"
thiserror = "1.0"
